version: '3.1'

services:
  web:
    build: .
    ports:
      - "85:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: maBaseDeDonnees
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
